// Generated by CoffeeScript 1.9.3
var Stream, generator, inOrNot;

Stream = require('stream');

inOrNot = require('../inOrNot');

generator = function(n) {
  var i, next, s;
  s = new Stream;
  i = 1;
  next = function() {
    s.emit('data', {
      name: 'name ' + i,
      value: Math.floor((i + Math.random()) * 100),
      age: Math.floor(i * 100 * Math.random() % 70),
      n_value: i,
      grade: {
        name: 'grade ' + (i % 6 + 1)
      }
    });
    i++;
    if (i === n) {
      s.emit('end');
    } else {
      process.nextTick(next);
    }
  };
  s.readable = true;
  process.nextTick(next);
  return s;
};

generator(100).pipe(inOrNot["in"]([35, 36, 37, 38, 39, 40], 'age')).on('data', function(doc) {
  return console.log(doc);
}).once('end', function() {
  return console.log('end');
});

//# sourceMappingURL=test.js.map
